version: "3.2"
services:
  back:
    container_name: back
    image: zerobird/warmwave:latest
    restart: always
    ports:
      - 8080:8080

  front:
    container_name: front
    image: zerobird/warmwave_react:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - back